### ISSUE TITLE
Could not resolve dependencies for mq 7.5.0.2 and iib 9.0.0.5

### ISSUE THREAD

**Issue by datafile4** [zheng-wang/irontest#1]
I installed MQ and IIB libraries as it was written in wiki, and when run 

`mvn clean package -pl irontest-mqiib -am -P prod` 
I got an error: 
```java
[ERROR] Failed to execute goal on project irontest-mqiib: Could not resolve depe
ndencies for project io.irontest:irontest-mqiib:jar:0.5.2: Failed to collect dep
endencies at com.ibm:com.ibm.mq.jmqi:jar:[7.5.0.1,7.5.0.6]: No versions availabl
e for com.ibm:com.ibm.mq.jmqi:jar:[7.5.0.1,7.5.0.6] within specified range -> [H
elp 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal o
n project irontest-mqiib: Could not resolve dependencies for project io.irontest
:irontest-mqiib:jar:0.5.2: Failed to collect dependencies at com.ibm:com.ibm.mq.
jmqi:jar:[7.5.0.1,7.5.0.6]
        at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDe
pendencies(LifecycleDependencyResolver.java:221)
        at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resol
veProjectDependencies(LifecycleDependencyResolver.java:127)
        at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAr
eResolved(MojoExecutor.java:245)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:199)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProje
ct(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProje
ct(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThre
adedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(Lifecycl
eStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Laun
cher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.jav
a:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(La
uncher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:
356)
Caused by: org.apache.maven.project.DependencyResolutionException: Could not res
olve dependencies for project io.irontest:irontest-mqiib:jar:0.5.2: Failed to co
llect dependencies at com.ibm:com.ibm.mq.jmqi:jar:[7.5.0.1,7.5.0.6]
        at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(D
efaultProjectDependenciesResolver.java:180)
        at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDe
pendencies(LifecycleDependencyResolver.java:195)
        ... 23 more
Caused by: org.eclipse.aether.collection.DependencyCollectionException: Failed t
o collect dependencies at com.ibm:com.ibm.mq.jmqi:jar:[7.5.0.1,7.5.0.6]
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.collectDe
pendencies(DefaultDependencyCollector.java:291)
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.collectDepen
dencies(DefaultRepositorySystem.java:316)
        at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(D
efaultProjectDependenciesResolver.java:172)
        ... 24 more
Caused by: org.eclipse.aether.resolution.VersionRangeResolutionException: No ver
sions available for com.ibm:com.ibm.mq.jmqi:jar:[7.5.0.1,7.5.0.6] within specifi
ed range
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.filterVer
sions(DefaultDependencyCollector.java:648)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDe
pendency(DefaultDependencyCollector.java:394)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDe
pendency(DefaultDependencyCollector.java:363)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.process(D
efaultDependencyCollector.java:351)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.collectDe
pendencies(DefaultDependencyCollector.java:254)
        ... 26 more
```

**Comment by zheng-wang** [comment]
It looks like Maven could not find com.ibm.mq.jmqi.jar. 

Please have a check whether you can see this file on your machine

`${user.home}/.m2/repository/com/ibm/com.ibm.mq.jmqi/<MQ_Version>/com.ibm.mq.jmqi-<MQ_Version>.jar`

${user.home}/.m2 is Maven's local repository hosting downloaded and installed packages.

An example on Windows machine is

`C:\Users\Zheng\.m2\repository\com\ibm\com.ibm.mq.jmqi\7.5.0.6\com.ibm.mq.jmqi-7.5.0.6.jar`

Please notice that the directory might be hidden depending on your operating system settings.

**Comment by datafile4** [comment]
I found 2 files in this directory: `com.ibm.mq.jmqi-7.5.0.2.jar.lastUpdated `and `com.ibm.mq.jmqi-7.5.0.2.pom.lastUpdated`

**Comment by zheng-wang** [comment]
Ok, it seems the jar is not installed well. Please try to rerun the command

`mvn install:install-file -Dfile="<MQ_Home>/java/lib/com.ibm.mq.jmqi.jar" -DgroupId=com.ibm -DartifactId=com.ibm.mq.jmqi -Dversion=<MQ_Version> -Dpackaging=jar`

An example on Windows machine is

`mvn install:install-file -Dfile="C:\Program Files (x86)\IBM\WebSphere MQ\java\lib\com.ibm.mq.jmqi.jar" -DgroupId=com.ibm -DartifactId=com.ibm.mq.jmqi -Dversion=7.5.0.2 -Dpackaging=jar`

Successful installation should let you see the jar file (not the .lastUpdated files) in Maven local repo.

**Comment by datafile4** [comment]
It solved this error, but I got new. I build irontest on machine that does not have IIB and MQ installed, I copied jars from another machine. Could this be the cause of this error? 
```java
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] irontest-parent
[INFO] irontest-core-server
[INFO] irontest-core-ui
[INFO] irontest-mqiib
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building irontest-parent 0.5.2
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ irontest-parent ---
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building irontest-core-server 0.5.2
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ irontest-core-server ---
[INFO] Deleting C:\Users\emil.alasgarov\Code\irontest-0.5.2\irontest-core-server\target
[INFO]
[INFO] --- maven-resources-plugin:3.0.1:resources (default-resources) @ irontest-core-server ---
[WARNING] Using platform encoding (Cp1251 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory C:\Users\emil.alasgarov\Code\irontest-0.5.2\irontest-core-server\src\main\res
ources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ irontest-core-server ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding Cp1251, i.e. build is platform dependent!
[INFO] Compiling 93 source files to C:\Users\emil.alasgarov\Code\irontest-0.5.2\irontest-core-server\target\classes
[WARNING] /C:/Users/emil.alasgarov/Code/irontest-0.5.2/irontest-core-server/src/main/java/io/irontest/core/assertion/XPa
thAssertionVerifier.java:[3,41] com.sun.org.apache.xpath.internal.XPathException is internal proprietary API and may be
removed in a future release
[WARNING] /C:/Users/emil.alasgarov/Code/irontest-0.5.2/irontest-core-server/src/main/java/io/irontest/core/assertion/XPa
thAssertionVerifier.java:[74,34] com.sun.org.apache.xpath.internal.XPathException is internal proprietary API and may be
 removed in a future release
[WARNING] /C:/Users/emil.alasgarov/Code/irontest-0.5.2/irontest-core-server/src/main/java/io/irontest/utils/IronTestUtil
s.java: Some input files use unchecked or unsafe operations.
[WARNING] /C:/Users/emil.alasgarov/Code/irontest-0.5.2/irontest-core-server/src/main/java/io/irontest/utils/IronTestUtil
s.java: Recompile with -Xlint:unchecked for details.
[INFO]
[INFO] --- maven-resources-plugin:3.0.1:testResources (default-testResources) @ irontest-core-server ---
[WARNING] Using platform encoding (Cp1251 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory C:\Users\emil.alasgarov\Code\irontest-0.5.2\irontest-core-server\src\test\res
ources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ irontest-core-server ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ irontest-core-server ---
[INFO] No tests to run.
[INFO]
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ irontest-core-server ---
[INFO] Building jar: C:\Users\emil.alasgarov\Code\irontest-0.5.2\irontest-core-server\target\irontest-core-server-0.5.2.
jar
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building irontest-core-ui 0.5.2
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ irontest-core-ui ---
[INFO] Deleting C:\Users\emil.alasgarov\Code\irontest-0.5.2\irontest-core-ui\target
[INFO]
[INFO] --- maven-resources-plugin:3.0.1:resources (default-resources) @ irontest-core-ui ---
[WARNING] File encoding has not been set, using platform encoding Cp1251, i.e. build is platform dependent!
[WARNING] Using platform encoding (Cp1251 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 93 resources
[INFO] Copying 2 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ irontest-core-ui ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-resources-plugin:3.0.1:testResources (default-testResources) @ irontest-core-ui ---
[WARNING] Using platform encoding (Cp1251 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory C:\Users\emil.alasgarov\Code\irontest-0.5.2\irontest-core-ui\src\test\resourc
es
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ irontest-core-ui ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ irontest-core-ui ---
[INFO] No tests to run.
[INFO]
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ irontest-core-ui ---
[INFO] Building jar: C:\Users\emil.alasgarov\Code\irontest-0.5.2\irontest-core-ui\target\irontest-core-ui-0.5.2.jar
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building irontest-mqiib 0.5.2
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ irontest-mqiib ---
[INFO] Deleting C:\Users\emil.alasgarov\Code\irontest-0.5.2\irontest-mqiib\target
[INFO]
[INFO] --- maven-resources-plugin:3.0.1:resources (default-resources) @ irontest-mqiib ---
[WARNING] File encoding has not been set, using platform encoding Cp1251, i.e. build is platform dependent!
[WARNING] Using platform encoding (Cp1251 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 2 resources to assets/app/views
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ irontest-mqiib ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding Cp1251, i.e. build is platform dependent!
[INFO] Compiling 2 source files to C:\Users\emil.alasgarov\Code\irontest-0.5.2\irontest-mqiib\target\classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /C:/Users/emil.alasgarov/Code/irontest-0.5.2/irontest-mqiib/src/main/java/io/irontest/core/runner/MQTeststepRunn
er.java:[3,1] package com.ibm.mq does not exist
[ERROR] /C:/Users/emil.alasgarov/Code/irontest-0.5.2/irontest-mqiib/src/main/java/io/irontest/core/runner/MQTeststepRunn
er.java:[4,28] package com.ibm.mq.constants does not exist
[ERROR] /C:/Users/emil.alasgarov/Code/irontest-0.5.2/irontest-mqiib/src/main/java/io/irontest/core/runner/MQTeststepRunn
er.java:[112,26] cannot find symbol
  symbol:   class MQQueue
  location: class io.irontest.core.runner.MQTeststepRunner
[ERROR] /C:/Users/emil.alasgarov/Code/irontest-0.5.2/irontest-mqiib/src/main/java/io/irontest/core/runner/MQTeststepRunn
er.java:[128,13] cannot find symbol
  symbol:   class MQMessage
  location: class io.irontest.core.runner.MQTeststepRunner
[ERROR] /C:/Users/emil.alasgarov/Code/irontest-0.5.2/irontest-mqiib/src/main/java/io/irontest/core/runner/MQTeststepRunn
er.java:[156,13] cannot find symbol
  symbol:   class MQMessage
  location: class io.irontest.core.runner.MQTeststepRunner
[ERROR] /C:/Users/emil.alasgarov/Code/irontest-0.5.2/irontest-mqiib/src/main/java/io/irontest/core/runner/MQTeststepRunn
er.java:[180,28] cannot find symbol
  symbol:   class MQQueue
  location: class io.irontest.core.runner.MQTeststepRunner
[ERROR] /C:/Users/emil.alasgarov/Code/irontest-0.5.2/irontest-mqiib/src/main/java/io/irontest/core/runner/MQTeststepRunn
er.java:[180,50] cannot find symbol
  symbol:   class MQException
  location: class io.irontest.core.runner.MQTeststepRunner
[ERROR] /C:/Users/emil.alasgarov/Code/irontest-0.5.2/irontest-mqiib/src/main/java/io/irontest/core/runner/MQTeststepRunn
er.java:[199,29] cannot find symbol
  symbol:   class MQQueue
  location: class io.irontest.core.runner.MQTeststepRunner
[ERROR] /C:/Users/emil.alasgarov/Code/irontest-0.5.2/irontest-mqiib/src/main/java/io/irontest/core/runner/MQTeststepRunn
er.java:[199,51] cannot find symbol
  symbol:   class MQException
  location: class io.irontest.core.runner.MQTeststepRunner
[ERROR] /C:/Users/emil.alasgarov/Code/irontest-0.5.2/irontest-mqiib/src/main/java/io/irontest/core/runner/MQTeststepRunn
er.java:[30,32] cannot find symbol
  symbol:   variable CMQC
  location: class io.irontest.core.runner.MQTeststepRunner
[ERROR] /C:/Users/emil.alasgarov/Code/irontest-0.5.2/irontest-mqiib/src/main/java/io/irontest/core/runner/MQTeststepRunn
er.java:[30,9] cannot find symbol
  symbol:   variable MQException
  location: class io.irontest.core.runner.MQTeststepRunner
[ERROR] /C:/Users/emil.alasgarov/Code/irontest-0.5.2/irontest-mqiib/src/main/java/io/irontest/core/runner/MQTeststepRunn
er.java:[60,30] cannot find symbol
  symbol:   variable CMQC
  location: class io.irontest.core.runner.MQTeststepRunner
[ERROR] /C:/Users/emil.alasgarov/Code/irontest-0.5.2/irontest-mqiib/src/main/java/io/irontest/core/runner/MQTeststepRunn
er.java:[61,30] cannot find symbol
  symbol:   variable CMQC
  location: class io.irontest.core.runner.MQTeststepRunner
[ERROR] /C:/Users/emil.alasgarov/Code/irontest-0.5.2/irontest-mqiib/src/main/java/io/irontest/core/runner/MQTeststepRunn
er.java:[62,30] cannot find symbol
  symbol:   variable CMQC
  location: class io.irontest.core.runner.MQTeststepRunner
[ERROR] /C:/Users/emil.alasgarov/Code/irontest-0.5.2/irontest-mqiib/src/main/java/io/irontest/core/runner/MQTeststepRunn
er.java:[63,9] cannot find symbol
  symbol:   class MQQueueManager
  location: class io.irontest.core.runner.MQTeststepRunner
[ERROR] /C:/Users/emil.alasgarov/Code/irontest-0.5.2/irontest-mqiib/src/main/java/io/irontest/core/runner/MQTeststepRunn
er.java:[64,9] cannot find symbol
  symbol:   class MQQueue
  location: class io.irontest.core.runner.MQTeststepRunner
[ERROR] /C:/Users/emil.alasgarov/Code/irontest-0.5.2/irontest-mqiib/src/main/java/io/irontest/core/runner/MQTeststepRunn
er.java:[65,27] cannot find symbol
  symbol:   variable CMQC
  location: class io.irontest.core.runner.MQTeststepRunner
[ERROR] /C:/Users/emil.alasgarov/Code/irontest-0.5.2/irontest-mqiib/src/main/java/io/irontest/core/runner/MQTeststepRunn
er.java:[65,57] cannot find symbol
  symbol:   variable CMQC
  location: class io.irontest.core.runner.MQTeststepRunner
[ERROR] /C:/Users/emil.alasgarov/Code/irontest-0.5.2/irontest-mqiib/src/main/java/io/irontest/core/runner/MQTeststepRunn
er.java:[68,32] cannot find symbol
  symbol:   class MQQueueManager
  location: class io.irontest.core.runner.MQTeststepRunner
[ERROR] /C:/Users/emil.alasgarov/Code/irontest-0.5.2/irontest-mqiib/src/main/java/io/irontest/core/runner/MQTeststepRunn
er.java:[72,32] cannot find symbol
  symbol:   variable CMQC
  location: class io.irontest.core.runner.MQTeststepRunner
[ERROR] /C:/Users/emil.alasgarov/Code/irontest-0.5.2/irontest-mqiib/src/main/java/io/irontest/core/runner/MQTeststepRunn
er.java:[74,32] cannot find symbol
  symbol:   variable CMQC
  location: class io.irontest.core.runner.MQTeststepRunner
[ERROR] /C:/Users/emil.alasgarov/Code/irontest-0.5.2/irontest-mqiib/src/main/java/io/irontest/core/runner/MQTeststepRunn
er.java:[78,22] cannot find symbol
  symbol:   class MQException
  location: class io.irontest.core.runner.MQTeststepRunner
[ERROR] /C:/Users/emil.alasgarov/Code/irontest-0.5.2/irontest-mqiib/src/main/java/io/irontest/core/runner/MQTeststepRunn
er.java:[79,43] cannot find symbol
  symbol:   variable CMQC
  location: class io.irontest.core.runner.MQTeststepRunner
[ERROR] /C:/Users/emil.alasgarov/Code/irontest-0.5.2/irontest-mqiib/src/main/java/io/irontest/core/runner/MQTeststepRunn
er.java:[79,83] cannot find symbol
  symbol:   variable CMQC
  location: class io.irontest.core.runner.MQTeststepRunner
[ERROR] /C:/Users/emil.alasgarov/Code/irontest-0.5.2/irontest-mqiib/src/main/java/io/irontest/core/runner/MQTeststepRunn
er.java:[117,9] cannot find symbol
  symbol:   class MQMessage
  location: class io.irontest.core.runner.MQTeststepRunner
[ERROR] /C:/Users/emil.alasgarov/Code/irontest-0.5.2/irontest-mqiib/src/main/java/io/irontest/core/runner/MQTeststepRunn
er.java:[124,9] cannot find symbol
  symbol:   class MQPutMessageOptions
  location: class io.irontest.core.runner.MQTeststepRunner
[ERROR] /C:/Users/emil.alasgarov/Code/irontest-0.5.2/irontest-mqiib/src/main/java/io/irontest/core/runner/MQTeststepRunn
er.java:[124,39] cannot find symbol
  symbol:   class MQPutMessageOptions
  location: class io.irontest.core.runner.MQTeststepRunner
[ERROR] /C:/Users/emil.alasgarov/Code/irontest-0.5.2/irontest-mqiib/src/main/java/io/irontest/core/runner/MQTeststepRunn
er.java:[130,9] cannot find symbol
  symbol:   class MQMessage
  location: class io.irontest.core.runner.MQTeststepRunner
[ERROR] /C:/Users/emil.alasgarov/Code/irontest-0.5.2/irontest-mqiib/src/main/java/io/irontest/core/runner/MQTeststepRunn
er.java:[130,33] cannot find symbol
  symbol:   class MQMessage
  location: class io.irontest.core.runner.MQTeststepRunner
[ERROR] /C:/Users/emil.alasgarov/Code/irontest-0.5.2/irontest-mqiib/src/main/java/io/irontest/core/runner/MQTeststepRunn
er.java:[137,28] cannot find symbol
  symbol:   variable CMQC
  location: class io.irontest.core.runner.MQTeststepRunner
[ERROR] /C:/Users/emil.alasgarov/Code/irontest-0.5.2/irontest-mqiib/src/main/java/io/irontest/core/runner/MQTeststepRunn
er.java:[137,17] cannot access com.ibm.mq.jmqi.JmqiObject
  class file for com.ibm.mq.jmqi.JmqiObject not found
[ERROR] /C:/Users/emil.alasgarov/Code/irontest-0.5.2/irontest-mqiib/src/main/java/io/irontest/core/runner/MQTeststepRunn
er.java:[138,30] cannot find symbol
  symbol:   variable CMQC
  location: class io.irontest.core.runner.MQTeststepRunner
[ERROR] /C:/Users/emil.alasgarov/Code/irontest-0.5.2/irontest-mqiib/src/main/java/io/irontest/core/runner/MQTeststepRunn
er.java:[139,36] cannot find symbol
  symbol:   variable CMQC
  location: class io.irontest.core.runner.MQTeststepRunner
[ERROR] /C:/Users/emil.alasgarov/Code/irontest-0.5.2/irontest-mqiib/src/main/java/io/irontest/core/runner/MQTeststepRunn
er.java:[140,33] cannot find symbol
  symbol:   variable CMQC
  location: class io.irontest.core.runner.MQTeststepRunner
[ERROR] /C:/Users/emil.alasgarov/Code/irontest-0.5.2/irontest-mqiib/src/main/java/io/irontest/core/runner/MQTeststepRunn
er.java:[157,9] cannot find symbol
  symbol:   class MQMessage
  location: class io.irontest.core.runner.MQTeststepRunner
[ERROR] /C:/Users/emil.alasgarov/Code/irontest-0.5.2/irontest-mqiib/src/main/java/io/irontest/core/runner/MQTeststepRunn
er.java:[157,33] cannot find symbol
  symbol:   class MQMessage
  location: class io.irontest.core.runner.MQTeststepRunner
[ERROR] /C:/Users/emil.alasgarov/Code/irontest-0.5.2/irontest-mqiib/src/main/java/io/irontest/core/runner/MQTeststepRunn
er.java:[161,21] cannot find symbol
  symbol:   variable CMQC
  location: class io.irontest.core.runner.MQTeststepRunner
[ERROR] /C:/Users/emil.alasgarov/Code/irontest-0.5.2/irontest-mqiib/src/main/java/io/irontest/core/runner/MQTeststepRunn
er.java:[161,42] cannot find symbol
  symbol:   variable CMQC
  location: class io.irontest.core.runner.MQTeststepRunner
[ERROR] /C:/Users/emil.alasgarov/Code/irontest-0.5.2/irontest-mqiib/src/main/java/io/irontest/core/runner/MQTeststepRunn
er.java:[166,39] package CMQC does not exist
[ERROR] /C:/Users/emil.alasgarov/Code/irontest-0.5.2/irontest-mqiib/src/main/java/io/irontest/core/runner/MQTeststepRunn
er.java:[167,18] cannot find symbol
  symbol:   variable CMQC
  location: class io.irontest.core.runner.MQTeststepRunner
[ERROR] /C:/Users/emil.alasgarov/Code/irontest-0.5.2/irontest-mqiib/src/main/java/io/irontest/core/runner/MQTeststepRunn
er.java:[167,68] cannot find symbol
  symbol:   variable CMQC
  location: class io.irontest.core.runner.MQTeststepRunner
[ERROR] /C:/Users/emil.alasgarov/Code/irontest-0.5.2/irontest-mqiib/src/main/java/io/irontest/core/runner/MQTeststepRunn
er.java:[171,35] cannot find symbol
  symbol:   variable CMQC
  location: class io.irontest.core.runner.MQTeststepRunner
[ERROR] /C:/Users/emil.alasgarov/Code/irontest-0.5.2/irontest-mqiib/src/main/java/io/irontest/core/runner/MQTeststepRunn
er.java:[182,9] cannot find symbol
  symbol:   class MQGetMessageOptions
  location: class io.irontest.core.runner.MQTeststepRunner
[ERROR] /C:/Users/emil.alasgarov/Code/irontest-0.5.2/irontest-mqiib/src/main/java/io/irontest/core/runner/MQTeststepRunn
er.java:[182,46] cannot find symbol
  symbol:   class MQGetMessageOptions
  location: class io.irontest.core.runner.MQTeststepRunner
[ERROR] /C:/Users/emil.alasgarov/Code/irontest-0.5.2/irontest-mqiib/src/main/java/io/irontest/core/runner/MQTeststepRunn
er.java:[183,30] cannot find symbol
  symbol:   variable CMQC
  location: class io.irontest.core.runner.MQTeststepRunner
[ERROR] /C:/Users/emil.alasgarov/Code/irontest-0.5.2/irontest-mqiib/src/main/java/io/irontest/core/runner/MQTeststepRunn
er.java:[183,51] cannot find symbol
  symbol:   variable CMQC
  location: class io.irontest.core.runner.MQTeststepRunner
[ERROR] /C:/Users/emil.alasgarov/Code/irontest-0.5.2/irontest-mqiib/src/main/java/io/irontest/core/runner/MQTeststepRunn
er.java:[184,9] cannot find symbol
  symbol:   class MQMessage
  location: class io.irontest.core.runner.MQTeststepRunner
[ERROR] /C:/Users/emil.alasgarov/Code/irontest-0.5.2/irontest-mqiib/src/main/java/io/irontest/core/runner/MQTeststepRunn
er.java:[184,33] cannot find symbol
  symbol:   class MQMessage
  location: class io.irontest.core.runner.MQTeststepRunner
[ERROR] /C:/Users/emil.alasgarov/Code/irontest-0.5.2/irontest-mqiib/src/main/java/io/irontest/core/runner/MQTeststepRunn
er.java:[189,17] cannot find symbol
  symbol:   class MQException
  location: class io.irontest.core.runner.MQTeststepRunner
[ERROR] /C:/Users/emil.alasgarov/Code/irontest-0.5.2/irontest-mqiib/src/main/java/io/irontest/core/runner/MQTeststepRunn
er.java:[190,39] cannot find symbol
  symbol:   variable CMQC
  location: class io.irontest.core.runner.MQTeststepRunner
[ERROR] /C:/Users/emil.alasgarov/Code/irontest-0.5.2/irontest-mqiib/src/main/java/io/irontest/core/runner/MQTeststepRunn
er.java:[190,79] cannot find symbol
  symbol:   variable CMQC
  location: class io.irontest.core.runner.MQTeststepRunner
[ERROR] /C:/Users/emil.alasgarov/Code/irontest-0.5.2/irontest-mqiib/src/main/java/io/irontest/core/runner/MQTeststepRunn
er.java:[200,9] cannot find symbol
  symbol:   class MQGetMessageOptions
  location: class io.irontest.core.runner.MQTeststepRunner
[ERROR] /C:/Users/emil.alasgarov/Code/irontest-0.5.2/irontest-mqiib/src/main/java/io/irontest/core/runner/MQTeststepRunn
er.java:[200,46] cannot find symbol
  symbol:   class MQGetMessageOptions
  location: class io.irontest.core.runner.MQTeststepRunner
[ERROR] /C:/Users/emil.alasgarov/Code/irontest-0.5.2/irontest-mqiib/src/main/java/io/irontest/core/runner/MQTeststepRunn
er.java:[201,30] cannot find symbol
  symbol:   variable CMQC
  location: class io.irontest.core.runner.MQTeststepRunner
[ERROR] /C:/Users/emil.alasgarov/Code/irontest-0.5.2/irontest-mqiib/src/main/java/io/irontest/core/runner/MQTeststepRunn
er.java:[201,51] cannot find symbol
  symbol:   variable CMQC
  location: class io.irontest.core.runner.MQTeststepRunner
[ERROR] /C:/Users/emil.alasgarov/Code/irontest-0.5.2/irontest-mqiib/src/main/java/io/irontest/core/runner/MQTeststepRunn
er.java:[204,13] cannot find symbol
  symbol:   class MQMessage
  location: class io.irontest.core.runner.MQTeststepRunner
[ERROR] /C:/Users/emil.alasgarov/Code/irontest-0.5.2/irontest-mqiib/src/main/java/io/irontest/core/runner/MQTeststepRunn
er.java:[204,37] cannot find symbol
  symbol:   class MQMessage
  location: class io.irontest.core.runner.MQTeststepRunner
[ERROR] /C:/Users/emil.alasgarov/Code/irontest-0.5.2/irontest-mqiib/src/main/java/io/irontest/core/runner/MQTeststepRunn
er.java:[207,21] cannot find symbol
  symbol:   class MQException
  location: class io.irontest.core.runner.MQTeststepRunner
[ERROR] /C:/Users/emil.alasgarov/Code/irontest-0.5.2/irontest-mqiib/src/main/java/io/irontest/core/runner/MQTeststepRunn
er.java:[208,43] cannot find symbol
  symbol:   variable CMQC
  location: class io.irontest.core.runner.MQTeststepRunner
[ERROR] /C:/Users/emil.alasgarov/Code/irontest-0.5.2/irontest-mqiib/src/main/java/io/irontest/core/runner/MQTeststepRunn
er.java:[208,83] cannot find symbol
  symbol:   variable CMQC
  location: class io.irontest.core.runner.MQTeststepRunner
```

**Comment by zheng-wang** [comment]
Probably. If there is no MQ/IIB on the machine, you can replace the value of `-Dfile` parameter in the mvn install commands with corresponding file path. It is used to let Maven find the jar file to install into its local repo.

**Comment by datafile4** [comment]
I already did it. Maybe I need to import some other jars on which depend previously imported jars ?

**Comment by zheng-wang** [comment]
Just ensure these jars (as indicated on the wiki page) are installed
```
com.ibm.mq.jar
com.ibm.mq.jmqi.jar
com.ibm.mq.commonservices.jar
com.ibm.mq.pcf.jar
com.ibm.mq.headers.jar
connector.jar
ConfigManagerProxy.jar
ibmjsseprovider2.jar
```
Other dependencies will be downloaded by Maven automatically.

I have also updated the wiki to inform other people.

**Comment by datafile4** [comment]
I checked folders in `C:\Users\emil.alasgarov\.m2\repository\com\ibm`, all jars are in place. Connector is in `C:\Users\emil.alasgarov\.m2\repository\javax\resource\connector\1.3.0\connector-1.3.0.jar`. Error still persists.

**Comment by zheng-wang** [comment]
The error indicates that com.ibm.mq-7.5.0.2.jar and com.ibm.mq.jmqi-7.5.0.2.jar can not be found. These jars contains the classes MQQueue, MQMessage, etc. If you can see these jars in you local Maven repo, try to open them with a Zip software such as WinZip or WinRAR and check whether you can find classes com/ibm/mq/MQQueue, com/ibm/mq/MQMessage, etc.

**Comment by zheng-wang** [comment]
Or if you don't mind, send me the jar files through email, and I can try a build to see what's the problem.

**Comment by datafile4** [comment]
Thank you! I replaced jars with correct jars and build succeeded!

**Comment by zheng-wang** [comment]
Fantastic!

**Comment by zheng-wang** [comment]
Build process no longer needs 'mvn install'.
