### ISSUE TITLE
Java Exception error.

### ISSUE THREAD

**Issue by sooraj2589** [zheng-wang/irontest#12]
while starting the server, receving java runtime exception error

INFO  [2020-02-03 07:06:52,997] org.eclipse.jetty.server.Server: Started @2851ms
java.lang.RuntimeException: java.lang.NoSuchFieldException: sys_paths
        at io.irontest.IronTestApplication.run(IronTestApplication.java:137)
        at io.irontest.IronTestApplication.run(IronTestApplication.java:51)
        at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:43)
        at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
        at io.dropwizard.cli.Cli.run(Cli.java:78)
        at io.dropwizard.Application.run(Application.java:93)
        at io.irontest.IronTestApplication.main(IronTestApplication.java:55)

Set java path properly. What will be the issue?

**Comment by zheng-wang** [comment]
v0.12.3 does not work with Java 12, I have created a new release v0.12.4. Please have a try.

**Comment by zheng-wang** [comment]
Assuming issue has been resolved.
