### ISSUE TITLE
H2 Database error when trying to launch

### ISSUE THREAD

**Issue by abhi202088** [zheng-wang/irontest#32]
I have installed the pre-requisites and buided irontest using maven successfullly. But when i try to launch the application, I am getting h2 database error stating "Table version not found".

`C:\NCS\IronTest\IronTest_Home>java -Djava.net.useSystemProxies=true -Xdebug -jar irontest-0.15.0.jar server config.yml
INFO  [2020-09-24 20:38:06,401] io.dropwizard.server.DefaultServerFactory: Registering jersey handler with root path prefix: /
INFO  [2020-09-24 20:38:06,406] io.dropwizard.server.DefaultServerFactory: Registering admin handler with root path prefix: /
INFO  [2020-09-24 20:38:06,406] io.dropwizard.assets.AssetsBundle: Registering AssetBundle with name: ui for path /ui/*
INFO  [2020-09-24 20:38:06,422] io.dropwizard.assets.AssetsBundle: Registering AssetBundle with name: lib for path /ui/lib/*
INFO  [2020-09-24 20:38:06,422] io.dropwizard.assets.AssetsBundle: Registering AssetBundle with name: mockserver for path /ui/mockserver/*
INFO  [2020-09-24 20:38:06,422] io.dropwizard.assets.AssetsBundle: Registering AssetBundle with name: common for path /ui/common/*
org.jdbi.v3.core.statement.UnableToCreateStatementException: org.h2.jdbc.JdbcSQLException: Table "VERSION" not found; SQL statement:
select version from version [42102-196] [statement:"select version from version", rewritten:"select version from version", parsed:"ParsedSql{sql='select version from version', parameters=ParsedParameters{positional=false, parameterNames=[]}}", arguments:{positional:{}, named:{}, finder:[]}]
        at org.jdbi.v3.core.statement.SqlStatement.internalExecute(SqlStatement.java:1422)
        at org.jdbi.v3.core.result.ResultProducers.lambda$getResultSet$2(ResultProducers.java:68)
        at org.jdbi.v3.core.result.ResultIterable.lambda$of$0(ResultIterable.java:53)
        at org.jdbi.v3.core.result.ResultIterable.findOnly(ResultIterable.java:97)
        at io.irontest.utils.IronTestUtils.lambda$getSystemDBVersion$3(IronTestUtils.java:369)
        at org.jdbi.v3.core.Jdbi.withHandle(Jdbi.java:318)
        at io.irontest.utils.IronTestUtils.getSystemDBVersion(IronTestUtils.java:366)
        at io.irontest.IronTestApplication.checkVersion(IronTestApplication.java:150)
        at io.irontest.IronTestApplication.run(IronTestApplication.java:117)
        at io.irontest.IronTestApplication.run(IronTestApplication.java:54)
        at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:43)
        at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
        at io.dropwizard.cli.Cli.run(Cli.java:78)
        at io.dropwizard.Application.run(Application.java:93)
        at io.irontest.IronTestApplication.main(IronTestApplication.java:58)
Caused by: org.h2.jdbc.JdbcSQLException: Table "VERSION" not found; SQL statement:
select version from version [42102-196]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
        at org.h2.message.DbException.get(DbException.java:179)
        at org.h2.message.DbException.get(DbException.java:155)
        at org.h2.command.Parser.readTableOrView(Parser.java:5552)
        at org.h2.command.Parser.readTableFilter(Parser.java:1266)
        at org.h2.command.Parser.parseSelectSimpleFromPart(Parser.java:1946)
        at org.h2.command.Parser.parseSelectSimple(Parser.java:2095)
        at org.h2.command.Parser.parseSelectSub(Parser.java:1940)
        at org.h2.command.Parser.parseSelectUnion(Parser.java:1755)
        at org.h2.command.Parser.parseSelect(Parser.java:1743)
        at org.h2.command.Parser.parsePrepared(Parser.java:449)
        at org.h2.command.Parser.parse(Parser.java:321)
        at org.h2.command.Parser.parse(Parser.java:293)
        at org.h2.command.Parser.prepareCommand(Parser.java:258)
        at org.h2.engine.Session.prepareLocal(Session.java:578)
        at org.h2.engine.Session.prepareCommand(Session.java:519)
        at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1204)
        at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:73)
        at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:677)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.apache.tomcat.jdbc.pool.ProxyConnection.invoke(ProxyConnection.java:126)
        at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:108)
        at org.apache.tomcat.jdbc.pool.interceptor.AbstractCreateStatementInterceptor.invoke(AbstractCreateStatementInterceptor.java:75)
        at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:108)
        at org.apache.tomcat.jdbc.pool.DisposableConnectionFacade.invoke(DisposableConnectionFacade.java:81)
        at com.sun.proxy.$Proxy36.prepareStatement(Unknown Source)
        at org.jdbi.v3.core.statement.DefaultStatementBuilder.create(DefaultStatementBuilder.java:57)
        at org.jdbi.v3.core.statement.SqlStatement.internalExecute(SqlStatement.java:1414)
        ... 14 more`

**Comment by zheng-wang** [comment]
Sorry there is a defect in the build. Please refer to the [release note](https://github.com/zheng-wang/irontest/releases/tag/v0.15.0) for steps to fix it.

**Comment by abhi202088** [comment]
Thanks. I missed that one. Is there any way that we can change the port number associated with the IronTest UI as McAfee is running on the same port already and I dont have admin access to change the port of McAfee.

**Comment by zheng-wang** [comment]
Assuming issue has been resolved.
